### ISSUE TITLE
How to reproduce tiny-imagenet results

### ISSUE THREAD

**Issue by zbh2047** [shizhouxing/Fast-Certified-Robust-Training#1]
Hi,  thank you for pushing the code! It's really a nice work. 

When I try to run the tiny-imagenet experiments, it seems that I cannot run this code normally. I use the command in `Readme` as follows:

`python train.py --method=fast --dir=model_tinyimagenet --scheduler_opts=start=2,length=20 --lr-decay-milestones=60,70 --num-epochs=80 --num_class=200 --config=config/tinyimagenet.ibp.json --model=cnn_7layer_bn`

There might be a few bugs listed below:

1) (Easily fixed) The batch size parameter has to be specified in `args`, rather than only in the config file `tinyimagenet.ibp.json`. Otherwise a traceback said that 'batch_size' is not defined in line 156 of `train.py`;
2) (Easily fixed) The model for TinyImagenet might be `cnn_7layer_bn_imagenet` instead of `cnn_7layer_bn` since the latter only has 10 logits;
3) After fixing the above typos, I still cannot run the code. The error is as follows:
in `certified.py`, line 23, `NameError: name 'get_spec_matrix' is not defined`.

I have installed the `auto_LiRPA` library. Could you please tell me if I missed something? Also, I would be appreciated if a detailed command about the best hyper-parameter is provided.

Thank you very much!

**Comment by YihanWang617** [comment]
> Hi, thank you for pushing the code! It's really a nice work.
> 
> When I try to run the tiny-imagenet experiments, it seems that I cannot run this code normally. I use the command in `Readme` as follows:
> 
> `python train.py --method=fast --dir=model_tinyimagenet --scheduler_opts=start=2,length=20 --lr-decay-milestones=60,70 --num-epochs=80 --num_class=200 --config=config/tinyimagenet.ibp.json --model=cnn_7layer_bn`
> 
> There might be a few bugs listed below:
> 
> 1. (Easily fixed) The batch size parameter has to be specified in `args`, rather than only in the config file `tinyimagenet.ibp.json`. Otherwise a traceback said that 'batch_size' is not defined in line 156 of `train.py`;
> 2. (Easily fixed) The model for TinyImagenet might be `cnn_7layer_bn_imagenet` instead of `cnn_7layer_bn` since the latter only has 10 logits;
> 3. After fixing the above typos, I still cannot run the code. The error is as follows:
>    in `certified.py`, line 23, `NameError: name 'get_spec_matrix' is not defined`.
> 
> I have installed the `auto_LiRPA` library. Could you please tell me if I missed something? Also, I would be appreciated if a detailed command about the best hyper-parameter is provided.
> 
> Thank you very much!

Hi, thank you for pointing out the issues! For 1 and 2, the command should be updated as
`python train.py --method=fast --config=config/tinyimagenet.ibp.json --model=cnn_7layer_bn_imagenet --scheduler_name=SmoothedScheduler --scheduler_opts=start=2,length=20 --reg-lambda=2e-1 --num-epochs=80  --lr-decay-milestones=61,71 --num-class 200 --grad-acc-steps=2 --batch-size=128`

**Comment by shizhouxing** [comment]
Hi @zbh2047 , sorry the current code requires a newer version of auto_LiRPA which we will release recently. I'll let you know when the new version is public. Thanks!

**Comment by zbh2047** [comment]
Thank you! Look forward to your update.

**Comment by shizhouxing** [comment]
Hi @zbh2047 , you may upgrade with `pip install --upgrade auto-LiRPA` now.

**Comment by zbh2047** [comment]
Thanks! Now it runs normally. By the way, I try the following command to reproduce the CIFAR-10 best result (based on the Readme):
`python train.py --method=fast --dir=model_cifar --scheduler_name=SmoothedScheduler --scheduler_opts=start=2,length=80 --lr-decay-milestones=120,140 --num-epochs=160 --num-class 10 --batch-size=128 --config=config/cifar.json --model=cnn_7layer_bn`

Are all hyper-parameters correct?  ( I'm a little bit afraid of missing hyper-parameters

**Comment by shizhouxing** [comment]
@zbh2047 If you want to run the model with full BNs then you need to set `--model cnn` or `--model cnn_7layer_bn2` (`cnn_7layer_bn` has one BN missing). Others look correct to me. Most hyperparameters have default values or can be automatically set. I think you may also just use:
```
python train.py --method=fast --dir=model_cifar --config=config/cifar.json --length=80 
```

**Comment by shizhouxing** [comment]
@zbh2047 Btw this work is based on IBP not CROWN-IBP (Table 2 in your new Linf paper).

**Comment by zbh2047** [comment]
@shizhouxing  Thanks for pointing out the issue! I will make corrections in the next version of the paper.
