### ISSUE TITLE
Consideration of Normalization on the Certified radius

### ISSUE THREAD

**Issue by AlgebraLoveme** [shizhouxing/Fast-Certified-Robust-Training#2]
Dear authors,

Hi! I went through your code for CIFAR10, and found that you applied a normalization with std=0.2 for it. However, there seems to be no adjustment of the certified radius with regard to it. Specifically, it seems that you certified 8/255 on the normalized data, which is equivalent to 8/255 * 0.2 = 1.6/255 certified radius for the original denormalized data. It could be that I overlooked the adjustment of radius, so could you please give some hints on where you consider this, and if not, why is this not necessary?

Thanks.

**Comment by shizhouxing** [comment]
We have considered the normalization in our certification. See https://github.com/shizhouxing/Fast-Certified-Robust-Training/blob/281f6d15e0f2ea4208be57746d060b314949c615/certified.py#L68-L69

**Comment by AlgebraLoveme** [comment]
Thanks. This is very helpful.
