### ISSUE TITLE
Model selection and validation set

### ISSUE THREAD

**Issue by AlgebraLoveme** [shizhouxing/Fast-Certified-Robust-Training#3]
Dear authors,

It seems that the training uses no validation set. Instead, it uses test data for test performance in every epoch. However, it seems that the best model is maintained via comparing the certified error on the test data. 

> https://github.com/shizhouxing/Fast-Certified-Robust-Training/blob/281f6d15e0f2ea4208be57746d060b314949c615/train.py#L222-L228

As far as I am concerned, this causes a fit to the test data, and a separate validation set should be used for this model selection. It could be that I misunderstood your intension, so could you please give some hints on this?

Thanks!

**Comment by shizhouxing** [comment]
I think it is fine as long as different methods (including baselines) are compared under the same evaluation. Previous works such as IBP and CROWN-IBP don’t seem to use a validation set either. If you prefer to use one, you may add it in your own work.
