### ISSUE TITLE
Non-zero tightness_0 for input node when epsilon=0?

### ISSUE THREAD

**Issue by AlgebraLoveme** [shizhouxing/Fast-Certified-Robust-Training#4]
Dear authors,

Hi! I am running your regularization, and wondering what is the meaning of
https://github.com/shizhouxing/Fast-Certified-Robust-Training/blob/281f6d15e0f2ea4208be57746d060b314949c615/regularization.py#L71

As far as I am concerned, this is the input slackness, i.e. eps / std. However, I write
```
    tightness_0 = ((node_inp.upper - node_inp.lower) / 2).mean()
    print(tightness_0.item(), eps)
```
to print its value in the first epoch of CIFAR training, it gets (the first three steps in the first epoch)
```4.937513040204067e-06 0.0
4.9462778406450525e-06 0.0
4.955990334565286e-06 0.0
4.93872539664153e-06 0.0
```
meaning that this is non-zero when eps is zero (eps=0 is expected as the first epoch is the standard training). This is really confusing me.

Could you please give some hints about why this is so and what is the exact meaning of
https://github.com/shizhouxing/Fast-Certified-Robust-Training/blob/281f6d15e0f2ea4208be57746d060b314949c615/regularization.py#L70

Thanks!

**Comment by shizhouxing** [comment]
Hi @AlgebraLoveme , 

When the regularization is used, a minimum non-zero epsilon is used when computing the bounds from the beginning, for the regularizer to take effect:
https://github.com/shizhouxing/Fast-Certified-Robust-Training/blob/main/certified.py#L67 
https://github.com/shizhouxing/Fast-Certified-Robust-Training/blob/main/parser.py#L17

` node_inp = modules['/input.1'] ` returns the input node, used to compute the tightness on the input layer and how the bounds get looser in later layers relative to the input layer.

**Comment by AlgebraLoveme** [comment]
Thanks! This is of great help! Do you mention this in the paper?  I  totally overlooked it after reading the paper.

In addition, I cannot find where does this min-eps-reg take effect. Could you show this as well?
https://github.com/shizhouxing/Fast-Certified-Robust-Training/blob/281f6d15e0f2ea4208be57746d060b314949c615/certified.py#L66
Here it seems that this only works when doing **not** robust training.

**Comment by shizhouxing** [comment]
`robust` is false for the first epoch when eps=0:
https://github.com/shizhouxing/Fast-Certified-Robust-Training/blob/281f6d15e0f2ea4208be57746d060b314949c615/train.py#L65-L66
In this case, a non-zero eps is still needed to compute the regularizers.

Sorry that it seems to have been missed in the paper. I should add it to Appendix C. Thanks for letting us know.

**Comment by AlgebraLoveme** [comment]
Thanks! This completely solves my confusion.
