### ISSUE TITLE
Training with L2Ball perturbations

### ISSUE THREAD

**Issue by pdebartol** [shizhouxing/Fast-Certified-Robust-Training#6]
Hi, thank you for the nice implementation!

I have been trying to run the method for perturbation sets other than Linf by changing the input perturbation layer:
```  
if args.norm == "Linf":
        data_ub = torch.min(data + eps, data_max) 
        data_lb = torch.max(data - eps, data_min) 
        ptb = PerturbationLpNorm(norm=np.inf, eps=eps, x_L=data_lb, x_U=data_ub)
elif args.norm == "L2":
        ptb = PerturbationLpNorm(norm=2, eps=eps, x_L=data, x_U=data)
else:
        raise NotImplementedError
 ```
 
 However, I get an error if I use any Lp ball other than Linf. This is for example the output of running MNIST with L2:
 ```
*** RuntimeError: Expected 3D (unbatched) or 4D (batched) input to conv2d, but got input of size: [1, 64, 1, 256, 64, 28, 28]
```

Thanks!

**Comment by shizhouxing** [comment]
Hello @pdebartol , are you using torch 2.0 or 1.13? There are some known issues in auto_LiRPA that we plan to fix in the next release. Could you please try torch 1.11 for now?

**Comment by shizhouxing** [comment]
Hi @pdebartol , I think auto_LiRPA has limited support for L2 norm and this code based on IBP is not intended for other norms either (IBP is more suitable for Linf or interval perturbations and may be much looser for other norms). 

If you do want to run L2 norm, I just checked the code and noticed that `eps` must be a scalar, and we don't need `x_L` and `x_U` for the L2-norm ptb:
```
ptb = PerturbationLpNorm(norm=2, eps=eps)
```

**Comment by pdebartol** [comment]
Thanks for the reply!  That solves the issue for MNIST but not for CIFAR unfortunately.
Do you know where does this problem come from?  I am aware these bounds are tighter for Linf but I didn't have any issue training CROWN-IBP and IBP with auto_LiRPA. 

This is the error I get now for CIFAR (once I pass epsilon as a scalar):

```
File "/cluster/home/pdebartol/.local/lib/python3.9/site-packages/auto_LiRPA/operators/convolution.py", line 234, in interval_propagate
    deviation = torch.mul(weight, weight).sum((1, 2, 3)).sqrt() * eps
RuntimeError: The size of tensor a (64) must match the size of tensor b (3) at non-singleton dimension 0
```

**Comment by shizhouxing** [comment]
For CIFAR I'm not sure if the eps here is really a scalar, because CIFAR has 3 input channels and each channel has a different normalization (standard deviation), and thereby eps also has 3 elements. 

I think this line `deviation = torch.mul(weight, weight).sum((1, 2, 3)).sqrt() * eps` needs to be rewritten. I'll push a fix.

For "training CROWN-IBP and IBP with auto_LiRPA", it looks like it has some correctness isusses as it probably doesn't consider the data normalization in the eps, if it's L2 norm, which also needs to be fixed.

**Comment by pdebartol** [comment]
Thanks, that's quite helpful! 
As for the data normalization, isn't it enough to scale eps by 1/std for correctness? (I am using (0.2,0.2,0.2) to avoid issues, see https://github.com/Verified-Intelligence/auto_LiRPA/issues/3 )

**Comment by shizhouxing** [comment]
@pdebartol Oh I see. Could you please check if your eps is now a scalar or something with 3 elements? 

`RuntimeError: The size of tensor a (64) must match the size of tensor b (3) at non-singleton dimension 0` seems to imply that your `eps` is 3 dimensions.

**Comment by pdebartol** [comment]
Sorry, my bad. Once you convert epsilon to a scalar the fix works for CIFAR as well, thanks!
